name: linear_step_indicator
description: A Flutter package for adding beautiful step indicators in your apps.
homepage: https://github.com/Crazelu/linear-step-indicator
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
